### ISSUE TITLE
pass all environment variables to client

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel-canon#11]

**Comment by jazzido** [comment]
watch out — we might want to pass private data to the app (db credentials, hostnames, etc)

**Comment by davelandry** [comment]
@jazzido I'm actually already passing the `CANON_API` environment variable to the store as `"API"`. I can easily add in non-sensitive variables, probably in a nested `"env"` object, but do you see a case where you would actually WANT private variables passed to the client? I'm not sure that is possible...

**Comment by jazzido** [comment]
Just realized that I mistyped my comment :) I meant to point out that we private stuff shout _not_ be passed to the client.

If we set DB creds as envvars, of course we don't want them to end up in a JSON blob in the browser.

**Comment by davelandry** [comment]
With the next update, there will be an "env" object in the store with the following environment variables:
* CANON_API
* CANON_ATTRS
* CANON_LANGUAGES
* CANON_LANGUAGE_DEFAULT
* CANON_LOGINS
* CANON_LOGREDUX
* CANON_PORT
* NODE_ENV
