### ISSUE TITLE
i18n states problem

### ISSUE THREAD

**Issue by palamago** [Datawheel/datawheel-canon#14]
Wild es-ES appears.
And differences between server and client depending on url subdomain changes.

<img width="752" alt="captura de pantalla 2017-07-21 a las 5 45 06 p m" src="https://user-images.githubusercontent.com/1203432/28483676-7c45c72e-6e3c-11e7-8e25-ece28c70218f.png">
<img width="733" alt="captura de pantalla 2017-07-21 a las 5 45 21 p m" src="https://user-images.githubusercontent.com/1203432/28483675-7c45dd0e-6e3c-11e7-81a1-e6c5ff06e41e.png">

**Comment by davelandry** [comment]
I'm having trouble testing this locally. Currently I'm using a Chrome plug-in (Quick Language Switcher) to switch languages from en to es. @palamago can you help me get subdomains set up in my local environment?

**Comment by palamago** [comment]
I changed my /etc/hosts file with this line:
127.0.0.1       datachile.local en.datachile.local es.datachile.local

**Comment by davelandry** [comment]
@palamago can you update to v0.9.3 and see if you're still getting this issue? I inadvertently found a i18n init bug while doing #21, and it may have fixed this!

**Comment by palamago** [comment]
Works great with v0.9.4 Thanks!
![i18n](https://user-images.githubusercontent.com/1203432/28871685-122be462-775c-11e7-89a6-8ccb452bf568.gif)
