### ISSUE TITLE
arabic language not being detected in chrome

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#20]
Try these steps:

0. Make sure Arabic is not listed in Chrome's languages (chrome://settings)
1. setup localization with english and arabic support "en,ar"
2. add the following lines to `/etc/hosts`
```
127.0.0.1 ar.ksatest.io
127.0.0.1 en.ksatest.io
```
3. add a component requiring translations.
4. run `npm run locales`
5. run the project

Goto `http://ar.ksatest.io:3300/<your page>`

Now, add Arabic to Chrome:

1. chrome://settings
2. Search "lang"
3. Select languages
4. "add languages" > Add Arabic (**Note** if Arabic is not added to the top of the list, Arabic will not be detected by canon/i18next!)

Try `http://ar.ksatest.io:3300/<your page>`

It will now recognize the `ar` locale

**Comment by davelandry** [comment]
@jspeis can you update to v0.9.3 and see if you're still getting this issue? I inadvertently found a i18n init bug while doing #21, and it may have fixed this!

**Comment by jspeis** [comment]
I upgraded to v0.9.4 but I'm still having issues

**Comment by davelandry** [comment]
@jspeis again, I fixed another i18n bug with v0.9.5. Curious if it fixes this bug :-)

**Comment by jspeis** [comment]
just tested with v0.9.6 and looks like its working now
