### ISSUE TITLE
Update to use react-router v4

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/datawheel-canon#24]
React-router v4 is a complete rewrite and definitely not a drop-in replacement esp for SSR! Grrrrr..., luckily, I found this tutorial for someone updating to v4 with some helpful gotchas:

http://crypt.codemancers.com/posts/2017-06-03-reactjs-server-side-rendering-with-router-v4-and-redux/

**Comment by davelandry** [comment]
@alexandersimoes are there any features you're looking to use in v4 that aren't available in v3?

Based on the way the community is going, and how difficult it is to work with react-router, @jazzido and I had discussed implementing our own router. It's actually fairly straightforward (and probably easier than upgrading to v4). I had tried to upgrade to v4 earlier this year, but ended up rolling back to v3 after I couldn't get it working with our stack.
