### ISSUE TITLE
Allow customization of login button text (i18n support)

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/datawheel-canon#25]
Currently on instantiation of a canon login you are stuck with english on all your buttons. It would be nice to be able to pass thru custom text for all the buttons. See below (from codelife):

![screen shot 2017-08-08 at 12 41 01 pm](https://user-images.githubusercontent.com/252276/29083693-8e8d6708-7c37-11e7-90b7-b188f885f4a9.png)

**Comment by davelandry** [comment]
All text and errors in the Login and SignUp components are now hooked up for localization.
