### ISSUE TITLE
optimize build process / differential builds?

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#26]
on a full server restart is there anyway we could cache part of the build so that only code that has changed since last build, gets rebuilt? seems like each time you restart an entire rebuild occurs (is this the case?), and doing a lot of server-side stuff I find myself needing to reboot somewhat frequently.

**Comment by davelandry** [comment]
Yes, an entire rebuild is triggered when changing server-side code. I would LOVE to get some sort of caching in there, I'm sure it exists somewhere.

**Comment by jspeis** [comment]
this looks interesting https://bendyworks.com/blog/optimizing-ci-and-webpack
