### ISSUE TITLE
API error when missing trailing slash in API env variable

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#3]
I got the following API error when missing trailing slash in the API env variable:

```
(node:86106) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: connect ECONNREFUSED 127.0.0.1:80
(node:86106) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The problem was I forgot a trailing slash in 
```
defaultExport.API = "http://localhost:5000/"
```

It would be great to check and add as needed!

**Comment by davelandry** [comment]
after looking at this, I think this is actually something that would need to get caught by the project using canon. I think this error was caused by the very next line in the project env that creates the ATTRS variable using the API variable
