### ISSUE TITLE
"private computer" de-authentication

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/datawheel-canon#31]
Something that we've encountered with our codelife logins is that when users login using Facebook, even after they've "logged out" of the application all subsequent facebook logins will automatically be authenticated (unprompted). Though this may be desirable for some sites, on codelife it is not, since often times the students will be using shared computers and logging them in with the previous users credentials could feel like a security issue for them.

Here's an article showing how to force a prompt everytime: https://stackoverflow.com/questions/12873960/passport-js-facebook-strategy-logout-issue

But I'd want to know how the rest of you guys feel about this... if we're divided, we could implement a flag as an env var.

**Comment by davelandry** [comment]
I feel like that should be the desired behavior. @jspeis what do you think?

**Comment by jspeis** [comment]
I think that's fine to have by default, in implementations of the sites would be nice to have an option where I user pass along a parameter to say "this is my private computer" / "keep me logged in"

**Comment by davelandry** [comment]
closing in favor of #80
