### ISSUE TITLE
Ability to specify redirect route post successful login

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/datawheel-canon#36]
Currently using canon logins after a successful the user is just redirected to the root homepage. If would be nice to give a hook for the user to specify this, something like:

```js
import {Login} from "datawheel-canon";

render() {
  <Login redirectTo="/user/settings" />
}
```

**Comment by davelandry** [comment]
`<Login />` and `<Signup />` components now have a "redirect" prop that can be set:

```jsx
<Login redirect="/user/settings" />
```

Additionally, to set the redirect for social logins, an environment variable is needed:

```sh
export CANON_SOCIAL_REDIRECT="/user/settings"
```
