### ISSUE TITLE
allow sections within CanonComponent topics to pass additional parameters

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#37]
It will be helpful for the `sections` within the `topics` props of `CanonComponent` to be able pass parameters through to `CanonComponent`, possibly for things like `shortTitle` values (or maybe in the future we want to mark a recently added section as "new" in the side-nav)

so having the ability to pass something through like:
```js
const topics = [
      {
        slug: "labor-force",
        title: t("Labor Force"),
        sections: [
          ComponentA,
          {component: ComponentB, shortTitle: t("Labor")}
       ]
}];
```

**Comment by davelandry** [comment]
@jspeis how do you feel about things like "shortTitle", "title", and "slug" being part of `defaultProps` for a component?

I've been trying to upgrade to the new version of React, and before the update we were able to grab the slug automatically from the name of the Component Class (things like "HarvestByValue") to be used in the anchor slugs. React 16 seems to remove that access, at least on the Server-Side rendering, so I'm considering switching the behavior over to defaultProps:

```js
HarvestByValue.defaultProps = {
  shortTitle: "Harvest",
  slug: "HarvestByValue",
  title: "Harvest by Value"
}
```

**Comment by jspeis** [comment]
That sounds good to me. In that case could we pass instantiations of the component (e.g. `<ComponentA />` instead of (or in addition to) `ComponentA`?  as that would be also likely make certain things, like translating default props easier to handle from within the component

**Comment by davelandry** [comment]
I haven't been able to get passing full instantiations working, because I believe React tries to render the component when you do that (and it only should be rendering from the actual return from the render function). How about something like this?

```js
const topics = [
      {
        slug: "labor-force",
        title: t("Labor Force"),
        sections: [
          ComponentA,
          {component: ComponentB, props: {shortTitle: t("Labor")}}
       ]
}];
```

**Comment by jspeis** [comment]
Sounds good!
