### ISSUE TITLE
standardized locales

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#39]
Sometimes locales are reported as "en" or "en-US" by the browser for example. Presumably this would allow differentiation between British/American English. Would be nice if for now, canon would only pass 2 character string before the dash for `locale`

**Comment by davelandry** [comment]
It should only be passing the first two characters of the locale, it actually explicitly strips off the hyphen and the last two characters here: https://github.com/Datawheel/datawheel-canon/blob/master/src/server.jsx#L49

@jspeis would you mind telling me more about what environment you're seeing this in? would love to hunt it down.

**Comment by jspeis** [comment]
I ran into this running on OS X using Chrome 61.0.3163.100. When I connected to the redux store's `state.i18n.locale` variable and on the homepage when no locale is specified the default locale is `en-US` but if I don't specify a locale and just say `?locale=en` the locale comes though as `en` as expected)
