### ISSUE TITLE
allow setting custom global constants

### ISSUE THREAD

**Issue by jazzido** [Datawheel/datawheel-canon#40]
Feature request from the Datachile team (@palamago and yours truly): it would be awesome to be able to define constants at **build** time (e.g. with Webpack's `DefinePlugin`).

Our use case is instantiating `MondrianClient` with a parameter that depends on whether the app is running on the server or the client. Thus, we need to define both. Yes, environment variables, but they're not present as global constants; they only exist in the Redux store.

Also, to avoid writing yucky things like `if (window)…`, we'd love to have a `IS_SERVER` constant (trivially easy to do from Webpack's configuration).

**Comment by davelandry** [comment]
Well isn't it your lucky day, I'm already using that plug-in (albeit very sparingly): https://github.com/Datawheel/datawheel-canon/blob/master/webpack/webpack.config.prod.js#L122

I think those variables should be refactored into two different Boolean variables: `__SERVER__` and `__DEV__`. Anything else you need in there for right now?

And also, to continue the idea, is there a preferred way of passing constants to there? Maybe through some environment variable prefix that I can scrape? Something like `CANON_CONST_*` gets transformed to `__*__`?
