### ISSUE TITLE
Global Mixins error during compilation

### ISSUE THREAD

**Issue by palamago** [Datawheel/datawheel-canon#41]
I want to define some global mixins to be used from other components' css later.

I did it on App.css, assuming that it is the first loaded component.

```css
@define-mixin for-xl {
  @media (max-width: 1800px) { @mixin-content; }
}
```

It works. But...

... `sometimes` during the webpack/postcss build in `npm run dev` I receive this error:

```shell
Module build failed: Syntax Error
(207:1) Undefined mixin for-xl
  205 |
  206 |
> 207 | @add-mixin for-xl {
      | ^
  208 | }
```

Where should I write my mixins to be sure every other css has access to them?

**Comment by davelandry** [comment]
@palamago can you show where you are trying to use that mixin, along with your import statements? I was able to get it working with the following:

### app/mixins.css
```css
@define-mixin padding $amount {
  padding: $amount;
}
```

### app/Footer.css
```css
@import "./mixins";
footer {
  @mixin padding 25px;
}
```

**Comment by palamago** [comment]
Makes sense. Thanks.
