### ISSUE TITLE
npm dependency

### ISSUE THREAD

**Issue by hwchen** [Datawheel/datawheel-canon#54]
@alexandersimoes 

In order to get a more recent node than the one in the stable ubuntu repo, I've been using the instructions here:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04

I don't have commit rights here, so I couldn't edit the wiki directly (I think).

and installing a ppa.

**Comment by davelandry** [comment]
@hwchen I just added you as a collaborator (anyone can edit public repo wikis, but only collaborators for private repos)

are you just looking to update the deployment section of the wiki?
