### ISSUE TITLE
add init script to scaffold project

### ISSUE THREAD

**Issue by nbond211** [Datawheel/datawheel-canon#69]
There should be an init script that scaffolds the initial project structure like how `create-react-app` works.

**Comment by jazzido** [comment]
Good ol' [Yeoman](http://yeoman.io/) is perfect for this.

**Comment by davelandry** [comment]
Will be part of the next release as the `canon-setup` script, available in fresh repos like this:

```bash
node node_modules/datawheel-canon/bin/setup.js
```

It currently does the following:
* sets up a simple `app/` directory, 
* adds a `static/` directory with a starter favicon
* adds the canon scripts to your `package.json`
* `.gitignore`
* `.eslintrc`
