### ISSUE TITLE
Allow multi-language sites to use react-router param to set language

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/datawheel-canon#78]
For the OEC we don't have access to the DNS thus preventing us from using a subdomain to set the language but we need to set it in the URL for SEO purposes.

A country profile URL with language set would look like: `/en/profile/country/pak/`

By adding a hook in canon we could set the language to a react-router param.

**Comment by davelandry** [comment]
Here's where I think this logic should reside: https://github.com/Datawheel/datawheel-canon/blob/master/src/server.jsx#L65

We'll have to detect for specific react-router params, hopefully available in the `req` object. How about just `lang` for now?
